name       : haskell-bindings-uname
version    : 0.1
release    : 2
source     :
    - http://hackage.haskell.org/package/bindings-uname-0.1/bindings-uname-0.1.tar.gz : 130e75c3fd95e232452c7d903efbfab2d2ff6c9d455b617adeaebe5d60235cd3
license    : PublicDomain
component  : programming.haskell
summary    : Low-level binding to POSIX uname(3)
description: |
    Low-level binding to POSIX uname(3)
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
